// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijgrizsbxnevkngbidew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZ3JpenNieG5ldmtuZ2JpZGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MDQyNTgsImV4cCI6MjA3MjE4MDI1OH0.to1ThlGsH5ijt7SKD7AarPAaijRLxUhQtdTqd2R8qKA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});